export const LocalMessages = {
  messages: {
    "1": "Invalid input",
    "2": "This field is required.",
    "3": "Your changes have not been saved yet. Do you want to move anyway?",
    "4": "Invalid email",
    "5": "This email has been registered with another user. Please try another one.",
    "6": "This username has already existed in the system. Please try another one.",
    "7": "Password must contain at least 8 characters.",
    "8": "Passwords don't match.",
    "9": "Successfully deleted",
    "10": "Delete failed, please try again.",
    "11": "Successfully updated",
    "12": "Update failed, please try again.",
    "13": "Successfully saved",
    "14": "Save failed, please try again.",
    "15": "Please fill in the required field(s).",
    "16": "Password has been successfully changed.",
    "17": "Change failed, please try again.",
    "18": "%s has been successfully created.",
    "19": "Creation failed, please try again.",
    "20": "Successfully connected",
    "21": "Connection failed",
    "22": "No results found",
    "23": "%s will be deleted, are you sure?",
    "24": "%s will be deleted, are you sure?",
    "25": "This chiller plant name has already existed. Please try another one.",
    "27": "Chillier plant was successfully imported.",
    "28": "Unable to import the chiller plant, please try again.",
    "29": "This equipment name has already existed. Please try another one.",
    "30": "The maximum number of chiller units is 10.",
    "31": "The maximum number of CTs is 10.",
    "32": "Chiller plant was successfully exported.",
    "33": "Unable to export the chiller plant, please try again.",
    "34": "%s will be deleted, are you sure?",
    "35": "%s has already existed. Please try another one.",
    "36": "Date in month must be filled",
    "37": "Duplicated date in month",
    "38": "Date in year must be filled",
    "39": "Duplicated date in year",
    "40": "Please select a weekday",
    "41": "Start time must be filled",
    "42": "Interval must be greater than zero.",
    "43": "Please fill in the time of Alert SMS",
    "45": "%s will be deleted, are you sure?",
    "46": "New image was successfully added.",
    "47": "Adding failed",
    "48": "Tag names were successfully collected.",
    "49": "Unable to collect tag names. Please check connection",
    "50": "%s will be deleted, are you sure?",
    "51": "Invalid 'Date'",
    "53": "Invalid 'Time'",
    "55": "Failed to update customer info, please try again",
    "56": "Your password has been successfully reset.",
    "57": "Failed to change password, please try again",
    "59": "Unable to view the report",
    "60": "Unable to download the report",
    "61": "%s will be deleted, are you sure?",
    "62": "Please choose an option for notification.",
    "63": "Report exported successfully",
    "64": "Failed to export the report",
    "65": "Key is valid",
    "66": "Invalid key",
    "67": "Account is valid",
    "68": "Invalid account",
    "69": "%s will be deleted, are you sure?",
    "70": "Invalid username or password",
    "73": "Reset password instruction has been sent to your email address.",
    "74": "Unable to send reset password instruction to your mail address.",
    "75": "Failed to reset password",
    "76": "Your password reset link has expired or already been used.",
    "77": "%s will be deleted, are you sure?",
    "78": "The new performance curve was successfully added. ",
    "79": "Failed to add the Performance Curve",
    "80": "This file name has already existed. Please try another one.",
    "90": "This image name has already existed. Please try another one.",
    "91": "Failed to upload file",
    "92": "Failed to update, because it was deleted by another user.",
    "93": "Failed to delete, because it was deleted by another user.",
    "94": "Failed to update, because it was changed by another user.",
    "95": "Failed to load, because it was changed by another user.",
    "96": "Invalid currency unit, chiller plant has only one currency unit.",
    "97": "Alert Time must be between 10 and 120 minutes",
    "98": "This equipment name has already existed. Please try another one.",
    "99": "This price ID has already existed. Please try another one.",
    "100": "Please input phone number",
    "101": "Please select country code",
    "102": "Invalid phone number",
    "103": "Invalid unit price value",
    "104": "This performance curve name has already existed. Please try another one.",
    "105": "The maximum number of CCTs is 10",
    "106": "Invalid file format, file format must be .JPEG or .PNG",
    "107": "Invalid file format, file format must be .CSV",
    "108": "Invalid file size, file size must be lower than or equal to 5MB",
    "109": "The Maximum Air Volume Rate must be greater than Minimum Air Volume Rate.",
    "110": "The Maximum Flow Rate must be greater than Minimum Flow Rate.",
    "111": "The Pecentage of Energy Saving must be more than 0 and less then 100.",
    "112": "The Period wihout Applying Set-Point must be more than 0.",
    "113": "Do you want to save your changes ?",
    "114": "Invalid server mail",
    "115": "This phone number has already existed. Please try another one.",
    "116": "Incorrect current password",
    "117": "Please choose a customer",
    "118": "Please choose a chiller plant",
    "119": "Please choose a building",
    "120": "Please choose a report type",
    "123": "The new phone number was successfully added.",
    "124": "Failed to add the new phone number",
    "125": "The new email was successfully added.",
    "126": "Failed to add the new email",
    "127": "This phone number has already existed. Please try another one.",
    "128": "This email has already existed. Please try another one.",
    "129": "Failed to download file.",
    "130": "%s will be deleted, are you sure?",
    "131": "Unable to delete %s because being used by chiller plant",
    "132": "Invalid file format, file format must be .XLSX",
    "133": "Successfully Uploaded",
    "134": "Invalid file. Please try another one.",
    "135": "Connection was interrupted, Please try again"
  }
}
